
import * as esbuild from "esbuild";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
const workRoot = fs.mkdtempSync(path.join(os.tmpdir(), "daemon-probe-"));
esbuild.buildSync({ entryPoints: [new URL("../src/daemon-sidecar.ts", import.meta.url).pathname], bundle: true, format: "cjs", platform: "node", target: "node18", outfile: path.join(workRoot, "s.cjs"), logLevel: "silent" });
const { DaemonSidecar } = require(path.join(workRoot, "s.cjs"));
const sidecar = new DaemonSidecar();
await sidecar.connect();
const events = [];
let id = null;
sidecar.onEvent = (m) => { if (m.activeSessionId !== id) return; if (m.type === "session_event") { events.push(m.event); console.log("EV", m.event?.type, JSON.stringify(m.event).slice(0, 300)); } };
const sessionDir = path.join(workRoot, "sessions"); fs.mkdirSync(sessionDir, { recursive: true });
const summary = await sidecar.request({ type: "create", lifecycle: "resident", config: { cwd: workRoot, sessionDir, model: "chutes/zai-org/GLM-4.7" } }, 45000);
id = summary.activeSessionId ?? summary.id;
console.log("created", id, JSON.stringify(summary).slice(0, 400));
const att = await sidecar.attach(id);
console.log("attached, snap messages:", att.snapshot?.messages?.length);
await sidecar.prompt(id, "Reply with exactly: PARITY-OK", "steer");
const deadline = Date.now() + 100000;
while (Date.now() < deadline && !events.some(e => e?.type === "agent_end")) await new Promise(r => setTimeout(r, 1000));
await new Promise(r => setTimeout(r, 2000));
const msgs = await sidecar.getMessages(id);
console.log("MESSAGES:", JSON.stringify(msgs, null, 1).slice(0, 4000));
await sidecar.request({ type: "kill", activeSessionId: id }, 15000).catch(e => console.log("kill err", e.message));
sidecar.dispose();
fs.rmSync(workRoot, { recursive: true, force: true });
process.exit(0);
